### ISSUE TITLE
[FeatureRequest] check for valid BIC/SWIFT (Bank Identifier Code)

### ISSUE THREAD

**Issue by DoubleU23** [Simplify/ibantools#1]
Alongside the IBAN, many services need an BIC/SWIFT code to identify the bank institute it belongs to.

It would be great if your plugin would support that.
Maybe you or somebody else (inclusive myself) will find time to implement that.

"specification":
https://en.wikipedia.org/wiki/ISO_9362

example regexp:
http://regexlib.com/REDetails.aspx?regexp_id=2768

**Comment by Simplify** [comment]
Hi @DoubleU23 ,

Thanks for creating this issue :)

I just released version 1.2.0. That includes:

* `isValidBIC(bic: string): boolean`
* `extractBIC(bic: string): Object {bankCode: string, countryCode: string, locationCode: string, branchCode: string, testBIC: boolean, valid: boolean} ` 

Let me know if this covers your needs.

**Comment by DoubleU23** [comment]
very nice!

thank you ;)
