### ISSUE TITLE
Use TypeScript strict flag

### ISSUE THREAD

**Issue by tkrotoff** [Simplify/ibantools#10]
Use TypeScript `strict` flag inside [tsconfig.json](https://github.com/Simplify/ibantools/blob/2.0.0/tsconfig.json), see https://www.typescriptlang.org/docs/handbook/compiler-options.html
This will among other things, tell tsc to check for null and undefined values: https://basarat.gitbooks.io/typescript/docs/options/strictNullChecks.html

**Comment by Simplify** [comment]
@tkrotoff Thanks for your report. `strict` flag is added to `tsconfig.json` file.
