### ISSUE TITLE
Incorrect example in the source code

### ISSUE THREAD

**Issue by electronicdreamer** [Simplify/ibantools#11]
It says in the source code that

`ibantools.isValidIBAN("NL91ABNA0517164300");`

should return `true` but it actually returns `false`.

Checking on https://www.ibancalculator.com/iban_validieren.html , it says

> The checksum in the account number is incorrect. But this is normal since Dutch accounts which were created after the introduction of the IBAN no longer need to pass the "elfproef" test.

So, should it really return true or false?

Thanks

**Comment by Simplify** [comment]
Hi @electronicdreamer. Sorry coming so late to address this issue. As said, after introduction of IBAN, Dutch accounts no longer need to pass "elfproef". So this IBAN is valid.
Also, IBANTools does not validate account numbers that are part of IBAN.
