### ISSUE TITLE
extractBIC does not handle lower case input

### ISSUE THREAD

**Issue by edgarbjorntvedt** [Simplify/ibantools#12]
### Expected behavior
bic = 'dnbanokk'
ibantools.extractBIC(bic).valid === ibantools.isValidBIC(bic)

### Actual behavior
bic = 'dnbanokk'
ibantools.extractBIC(bic)
// throws TypeError: Cannot read property 'name' of undefined

**Comment by Simplify** [comment]
@edgarbjorntvedt thank you for reporting this and sorry that it took me almost 6 months to address this issue. Problem is solved and new version is available.
