### ISSUE TITLE
Vatican City IBAN not valid

### ISSUE THREAD

**Issue by icorne** [Simplify/ibantools#13]
Vatican City is  "newly" approved

### Expected behavior

VA59001123000012345678 to be valid

### Actual behavior

VA59001123000012345678 is invalid

### Steps to reproduce the behavior

ibantools.isValidIban('VA59001123000012345678')

**Comment by Simplify** [comment]
Hi @icorne,

Than you for reporting this. Vatican is added to the list and it will be available in next release (probably today). Sorry that it took so long.
