### ISSUE TITLE
friendlyFormatIBAN breaks if iban is undefined

### ISSUE THREAD

**Issue by gerjanvangeest** [Simplify/ibantools#15]
### Expected behavior

let iban = undefined;
let friendlyIban = friendlyFormatIBAN(iban);
console.log(friendlyIban); // undefined

### Actual behavior

ibantools.js:144 Uncaught TypeError: Cannot read property 'replace' of null

### Steps to reproduce the behavior

See expected behavior

**Comment by Simplify** [comment]
Hi @gerjanvangeest,

Thank you for reporting this. Issue is fixed, that function will return `null`, similar how `electronicFormatIBAN` behaves. Next version with this fix will be released today, or day after.

In version 3 I'll change behavior of this and few other functions to throw `TypeError` with message `invalid arguments` when invalid argument is provided.

**Comment by gerjanvangeest** [comment]
Thanks for the quick fix :)
