### ISSUE TITLE
Error minifying ibantools with webpack 2.2.1 and babel in production mode

### ISSUE THREAD

**Issue by ericstumper** [Simplify/ibantools#2]
Hi,

I was using ibantools just fine in dev mode with webpack 2.2.1 and babel-loader. Now I was trying to use it in my production bundle and got the following error:

```
ERROR in main.74ed3969cc257db12466.js from UglifyJs
SyntaxError: Unexpected token: name (countrySpecs) [main.74ed3969cc257db12466.js:24687,4]
```

Inspecting my bundle I find the following line:

```
// Country specifications
let countrySpecs = {};
```

It seems that babel is not transpiling the es6 correctly and uglify if then stumbling over the `let`.

I have no clue what the problem might be right now. All other libraries got transpiled just fine by now. Tried both ES6 imports and CommonJS requires.

**Comment by Simplify** [comment]
Hi @ericstumper,

UglifyJS does not support ES6. Using `let` will make problems and my guess is is that babel is not changing `let` to `var` in your configuration when transpiling. You can:

- Use [babili](https://github.com/webpack-contrib/babili-webpack-plugin) and not uglifyjs.
- Use bower package of ibantools. Npm package contains only ES6 version, bower package only ES5.
- Use [harmony branch](https://github.com/mishoo/UglifyJS2/tree/harmony) of uglifyjs that supports ES6. Add this to your `package.json`: `"uglify-js": "git://github.com/mishoo/UglifyJS2#harmony"`

Let me know if this helps or not. I may go back to bundling both ES5 and ES6 version of ibantools in npm package.

**Comment by ericstumper** [comment]
I just realised that you don't do any transpiling yourself on the ES2015 version. Right now the version that is referenced via jsnext:main is not supposed to contain any ES2015 code besides imports and exports, so that you don't have to run babel on all your node_modules on compilation or guess which library is already transpiled by the author:
See:
http://shuheikagawa.com/blog/2017/01/05/main-jsnext-main-and-module/
https://github.com/jsforum/jsforum/issues/5

I will try to include ibantools into my babel-loader config for now as an exception.

**Comment by Simplify** [comment]
Ok, that may be the problem, your configuration picks `jsnext:main` and there is `let` in `es6/ibantools.js`. 
I do provide ES2015 version, as `main` in `package.json`. It points to `build/ibantools.js`. 

You can edit `node_modules/ibantools/package.json` in your project and remove `jsnext:line` and see if that helps. I'll try to fix this in next few days by removing `jsnext:main` or by fixing output format that `tsc` generates if that is possible.

**Comment by ericstumper** [comment]
That would be great! Thanks a lot. I will use a fork with the `build/ibantools.js` version until you release an update.

**Comment by Simplify** [comment]
Hi @ericstumper 

I just release 1.3.0 that should fix problem with output for `jsnext:main` file. Let me know if this works for you.
