### ISSUE TITLE
IBAN for Cape Verde doesn't work

### ISSUE THREAD

**Issue by madebyrogal** [Simplify/ibantools#20]
### Expected behaviour
This IBAN seems to be correct
`CV27454373365156652975817`

### Actual behaviour
`isValidIBAN` return false for the IBAN nr above

### Steps to reproduce the behaviour
try to validate this IBAN nr `CV27454373365156652975817`
You can compare it with this validator:
https://www.iban.com/iban-checker

**Comment by Simplify** [comment]
Hi @madebyrogal,

Thank you for your bug report and sorry that took me so long to address it. 

Problem is that IBANTools included only countries that are included in official IBAN registry. I just added 25 "Experimental" IBAN countries (inc. Cape Verde). In next few days I'll make 3.0 release that will include this change.
