### ISSUE TITLE
Provide an es module version

### ISSUE THREAD

**Issue by daKmoR** [Simplify/ibantools#22]
### Expected behavior

That I can import it via native es modules like

```js
import { isValidIBAN } from 'ibantools';
```

### Actual behavior

no es module version is available

### Steps to reproduce the behavior

1. go to unpkg.com
2. open browser console (in a browser that supports native es modules)
3. write and hit enter
  ```js
  import('https://unpkg.com/ibantools@2.2.0/build/ibantools.js').then(module => {
    console.log(module.isValidIBAN('123'));
  });
  ```
==> 
```
ibantools.js:15 Uncaught (in promise) ReferenceError: exports is not defined
    at ibantools.js:15
```

### Workaround

use a separately built version for es modules [@bundled-es-modules/ibantools](https://www.npmjs.com/package/@bundled-es-modules/ibantools).

```js
import('https://unpkg.com/@bundled-es-modules/ibantools@2.0.0/index.js').then(module => {
  console.log(module.isValidIBAN('123'));
});
```

## Possible Solution

1. Provide an es module version via rollup and add it via the `module` field to the package.json
2. Change code to es modules and distribute it as is (+ create current commonjs bundle and maybe requirejs bundle for backwards compatibility)

**Comment by Simplify** [comment]
Hi @daKmoR, thank you for you report and sorry about my late response. 

IBANTools already contains ["module" field in `package.json`](https://github.com/Simplify/ibantools/blob/master/package.json#L15). It points to "jsnext/ibantools.js" that is included in NPM package but not in this repo.

On unpkg.com you can try this:
```js
import('https://unpkg.com/ibantools@2.2.0/jsnext/ibantools.js').then(module => {
  console.log(module.isValidIBAN('NL91ABNA0417164300'));
});
```

**Comment by daKmoR** [comment]
we already switched to it - thxx 💪🤗
