### ISSUE TITLE
Valid Seychelles IBAN considered incorrect

### ISSUE THREAD

**Issue by ashakhov** [Simplify/ibantools#26]
### Expected behavior
According to https://www.iban.com/structure and https://www.iban.com/iban-checker, following IBAN is correct:

- SC52BAHL01031234567890123456USD

### Actual behavior
isValidIBAN('SC52BAHL01031234567890123456USD') returns false

### Steps to reproduce the behavior
Use isValidIBAN('SC52BAHL01031234567890123456USD') and check result.

Checking getCountrySpecifications() for SC gives `bban_regexp: "^[[A-Z]{4}[]0-9]{20}[A-Z]{3}$"`.
I believe that the correct regexp for this case should rather be `^[A-Z]{4}[0-9]{20}[A-Z]{3}$`

**Comment by Simplify** [comment]
Hi @ashakhov,
Sorry for late reaction from me. You are right, regexp is the problem. It's fixed now and it will be available in next release.

**Comment by Simplify** [comment]
Version 3.1.0 released with fix.
