### ISSUE TITLE
IBAN with dashes does not validate

### ISSUE THREAD

**Issue by Koala-gentil** [Simplify/ibantools#273]
**Describe the bug**
When we enter this IBAN with the dashes the application timeout without any error.

**To Reproduce**
```js
const ibantools = require("ibantools")

const iban = 'FR76-4097-8265-8510-1221-2598-123'

const result = ibantools.validateIBAN(iban)
```

**Comment by Simplify** [comment]
Thank you for your report. Version 4.2.2 is released that fixes the issue.
