### ISSUE TITLE
not correct bic validation

### ISSUE THREAD

**Issue by Julian-B90** [Simplify/ibantools#3]
Hi @Simplify your regex for bic validation is not correct. 
For example NOLADE21KIE is a valid bic (https://www.foerde-sparkasse.de/de/home/toolbar/kontakt.html) but your function say it is not a valid bic.

**Comment by Simplify** [comment]
Hi @Julian-B90 thanks a lot for this report. I see where the problem is. I'll fix this today and make new release.

**Comment by Simplify** [comment]
Hi @Julian-B90,

This is solved and released in version 1.3.0.

**Comment by Julian-B90** [comment]
@Simplify great not it works. Thank you for fixing this.
