### ISSUE TITLE
QR-IBAN

### ISSUE THREAD

**Issue by endze1t** [Simplify/ibantools#332]
Hey, is there a way to detect QR-IBAN (https://www.banana.ch/apps/en/node/9387)? Our payment service provider does not support such QR-IBANs. 

Would be nice, if `isValidIBAN` could get an option like `disallowQR` or something like that, so that these IBAN's get marked as invalid.

**Comment by Simplify** [comment]
Yes, I'll try to implement it and make release in next few days.

**Comment by Simplify** [comment]
@endze1t Version 4.3.0 is published that adds support for QR-IBAN.

**Comment by endze1t** [comment]
Thank you!
