### ISSUE TITLE
BIC from IBAN?

### ISSUE THREAD

**Issue by puittenbroek** [Simplify/ibantools#37]
Hello, your tools looks very promising.
Question, can you calculate/extract the BIC code from an IBAN with your tool?
Don't see any examples for it, only to extract an IBAN or BIC from a string.

If it's not implemented, do you have any plans to do so?

**Comment by tarmooo** [comment]
substring from IBAN does not work for you?

**Comment by Simplify** [comment]
Hi @puittenbroek,

That feature is not planned and not possible for most IBAN numbers. 
BIC is made like this:
<4 chars bank code><2 chars country code><2 chars location code><sometimes up to 3 chars branch code>
Example: ABNANL2A
Dutch IBAN looks like this: NL91ABNA0517164300
<country code><checksum><bank code><account number>
It does not contain location code as far I know, so it's not possible to extract BIC up.

**Comment by puittenbroek** [comment]
Correct, you cannot derive the BIC directly from the IBAN. You'll always need to do some look up.
A python tool schwifty has a [json](https://github.com/mdomke/schwifty/blob/master/schwifty/bank_registry/generated_nl.json#L2-L8) file for this. So it looks up the BIC according to the bank code or branch code.

So anyway, thanks for your answer!
