### ISSUE TITLE
Incorrect code in mod9710Iban

### ISSUE THREAD

**Issue by simon-greatrix** [Simplify/ibantools#380]
This code is incorrect. It just happens to work:

```
function mod9710Iban(iban: string): number {
  return mod9710(replaceCharaterWithCode(iban.slice(3) + iban.slice(0, 4)));
}
```

As the correct procedure is to move the first FOUR characters, it should read `iban.slice(4)`.

Despite being incorrect, the code currently produces the correct result as this function is only used when generating the check digit. In this specific case the 3rd and 4th characters are both '0' so when one is erroneously included at the start it does not change the check digit.

I feel it would be better to do the correct thing in the function to prevent problems in the future if the function is used in other situations, (and because it being visibly wrong makes me feel uncomfortable, even if it happens to work :-) )

**Comment by SaichandChowdary** [comment]
PR for this issue - https://github.com/Simplify/ibantools/pull/385

**Comment by Simplify** [comment]
Hi @SaichandChowdary 
Thanks for your contribution and sorry about me getting too long to check this and merge.
