### ISSUE TITLE
Add support for Cape Verde iban validation

### ISSUE THREAD

**Issue by ggolubic** [Simplify/ibantools#39]
### Expected behavior

CV IBAN CV64 0003 0000 8885 5008 1017 6 to be valid

### Actual behavior

CV64 0003 0000 8885 5008 1017 6 is not valid because CV.IBANRegistry is marked as false in countries list but according to https://www.nordea.com/en/our-services/cashmanagement/iban-validator-and-information/iban-countries/ it an IBAN supported country.

### Steps to reproduce the behavior

Validate CV64 0003 0000 8885 5008 1017 6 with isValidIBAN function.
Also https://www.iban.com/iban-checker says it is valid.

**Comment by Simplify** [comment]
Thank you for bug report. Sorry that it took so long for me to respond. 
I just released 3.2.2 that fixes this issue.
