### ISSUE TITLE
Some more countries are using IBAN

### ISSUE THREAD

**Issue by ryancrunchi** [Simplify/ibantools#395]
List of countries using IBAN seems outdated.

From this website some countries are now using IBAN but ibantools IBANRegistry is returning false. (Few examples are BI, DJ, NI...)
https://www.iban.com/structure

Maybe there could be a script to update those informations automatically every month or quarter.

**Comment by Simplify** [comment]
@ryancrunchi thanks for reporting this!

List was updated few weeks ago, last version should contain everything already. I have added script that parses IBAN registry text file to generate some definitions for countries that are listed in registry. Some countries use IBAN, but are not part of official registry. 

Swift provides PDF and TXT file with registry specification. 
PDF contains change log only for last version and if you miss one, there is no way to know what was changed. They do not provide older versions of documents.
TXT is difficult to parse as it contains different encodings all over the place and it's not UTF-8. I think this is Excel dump. I did manage to use it, but don't trust it enough for code generation.
