### ISSUE TITLE
Indicate reason why text is not a valid IBAN

### ISSUE THREAD

**Issue by dantman** [Simplify/ibantools#40]
I would like to use `ibantools` to validate IBANs entered by a user in a text field.

`ibantools` offers `isValidIBAN`, however this only returns a boolean result. i.e. I can only tell the user "Please input a valid IBAN" in the error message.

However this is considered bad practice for forms. Best practice is to tell the user why what they entered is incorrect. For example:

- "Unknown IBAN country"
- "IBAN is too short"
- "IBAN is too long"
- "Invalid BBAN characters"
- "IBAN failed the checksum"

I would appreciate it if `ibantools` had a way to know why an IBAN was invalid, with a series of error codes (e.g. `invalid_country`, `invalid_length` with a copy of the `chars` number somewhere, `invalid_checksum`, etc). Any API for this is fine: an `error` on `extractIBAN`, an extra `validateIBAN` that throw an error with a `code` and extra info, or an extra function that returns an error info object.

**Comment by Simplify** [comment]
Thanks for this bug report. I'll address it in version `4.0.0` because this will change current API for sure. Hopefully in next week or two.

In the case when IBAN is invalid you will receive list of errors (one or more codes) and IBAN specification details (like IBAN length for instance), so you can construct your own error messages. In the case that checksum is invalid I'm not going to provide valid checksum in returning IBAN specs.

**Comment by dantman** [comment]
Thanks. I'm also going to be doing BIC codes so the same treatment for those would be good.

Isolatable error classes I can see:

- Wrong size (not 8 or 11 characters)
- Invalid characters in code
- Unknown country

**Comment by dantman** [comment]
My client has updated the specs a bit. I need to custom validate XX (country) IBANs and should validate the checksum for countries without a current IBAN format instead of considering them invalid.

Will that list of errors still validate the checksum for an invalid country so I can ignore specific errors? Or should I ask for `isValidIBANChecksum` to be exported?

**Comment by Simplify** [comment]
Hi @dantman Sorry that it took me so long.
I made PR that will add `validateIBAN` method. It will return object in format `{ valid: boolean, errorCodes: [] }`. 

If you need to custom validate country `XX`, you can add `XX` specification to `countrySpecs`.
Fox example:
```javacript
countrySpecs['XX'] = {
  chars: 28,
  bban_regexp: '^[0-9]{8}[A-Z0-9]{16}$',
  IBANRegistry: true,
  SEPA: true,
}
```

**Comment by dantman** [comment]
Thanks. That's a nice start. Miss the ability to differentiate between codes being too long and too short.

There is one bug. For the example code `US64SVBKUS6S3300958879` validateIBAN returns `[WrongBBANLength]` as the error.
