### ISSUE TITLE
License is too restrictive

### ISSUE THREAD

**Issue by melroy89** [Simplify/ibantools#429]
**Describe the problem**

This package, which is then used for many projects as a dependency is too restrictive (using MPL-2.0).

**Expected behavior**

MIT license. Or I won't use it.

**Comment by Simplify** [comment]
Explained here: https://github.com/Simplify/ibantools/discussions/335
If you don't like, don't use it.

**Comment by melroy89** [comment]
yea I won't.. too bad.
