### ISSUE TITLE
How to setup ibantools with Nuxt ?

### ISSUE THREAD

**Issue by gilles6** [Simplify/ibantools#45]
How to register `ibantools` with Nuxt ?
```
npm install ibantools
```

**Comment by Simplify** [comment]
I'm not familiar with Nuxt, but you can probably use it as any other npm package.

After adding ibantools to package.json you can do something as:

```javascript
import * as ibantools from 'ibantools';

const valid = ibantools.isValidIBAN('NL91 ABNA 0517 1643 00');
```
