### ISSUE TITLE
Validation is not correct for Dutch bank account number.

### ISSUE THREAD

**Issue by melihkorkmaz** [Simplify/ibantools#487]
**Describe the bug**
There seems to be an issue with the Dutch bank account number validation method using modulo in the [ibantools.ts script](https://github.com/Simplify/ibantools/blob/master/src/ibantools.ts#L919C14-L919C24). The current method sums up the digits of the account number and checks if the total is divisible by 11. Although this works in most cases, I've encountered a valid account number that fails this validation. This account number has been confirmed as valid through other platforms such as the ING Mobile app and the Wise website.

When I check in those applications it return validation true. but with a warning:
**The IBAN structure looks good, but the local bank account details could not be validated**
![Capture-2024-01-05-115112](https://github.com/Simplify/ibantools/assets/15940533/685ff8f2-f81f-4046-93f2-a9317955934c)

As I understand this is an issue but it does not mean the bank account is not valid.

**To Reproduce**
I cant share account number directly here since it's our customers account. But you can contact me for more details.

**Expected behavior**
The validation should accurately return 'true' for this valid account number.

**Environment:**

**Additional context**
I am prepared to contribute a pull request to address this issue, as it's impacting our production application. Your assistance in resolving this matter would be greatly appreciated. Thank you.

**Comment by greeeg** [comment]
I'd like to add that there might have been an issue in releasing `4.3.7` as it does not contain, at least for the `jsnext` output, the right code. Indeed, [this commit](https://github.com/Simplify/ibantools/commit/772c95efd4a3c920e639fb107768dca22873b62c) is only in the `4.3.8` `jsnext` build whereas it is in `4.3.7`.

**Comment by melihkorkmaz** [comment]
Thank you for answer. Yes downgrading to 4.3.7 fixed the issue. But do you have plan to update the package to validate edge cases? We really like to use up to date version of packages in our repo.

**Comment by Simplify** [comment]
I'll try to make release today. If not, there will be one tomorrow.

**Comment by Simplify** [comment]
New version (4.3.9) is released that removes elf-proof.
