### ISSUE TITLE
Andorra seems to be a SEPA country and it's not showing up as one for this library.

### ISSUE THREAD

**Issue by carlospnav** [Simplify/ibantools#49]
### Expected behavior

ibantools.isSEPACountry('AD')  to be truthy.

### Actual behavior

ibantools.isSEPACountry('AD') returns false.

### Steps to reproduce the behavior

You can look at the countrySpecs for Andorra and see it's not included as a SEPA country.

**Comment by carlospnav** [comment]
Furthermore, upon digging in deeper, it seems the following countries differ from the current SEPA classification (unless I'm missing something):
Andorra - AD -> Should be SEPA
Bulgaria - BG -> Should be SEPA

Faroe Islands - FO -> Should *not* be SEPA
Greeland - GL -> Should *not* be SEPA

This information seems to be all over the place though, so it's hard to find the proper source of truth for comparison.

**Comment by Simplify** [comment]
Thanks for reporting this and sorry about my late reaction. This is solved and will be released today.
