### ISSUE TITLE
Invalid BIC is detected as valid

### ISSUE THREAD

**Issue by FireEmerald** [Simplify/ibantools#5]
### Expected behavior
`.isValidBIC(INGDEFFXXX);` **Must** return **false**.
`.isValidBIC(INGDDEFFXXX);` Must return true.

### Actual behavior
`.isValidBIC(INGDEFFXXX);` Returns **true** (wrong).
`.isValidBIC(INGDDEFFXXX);` Returns true (correct).

### Steps to reproduce the behavior
```
var ibantools = require('ibantools');
ibantools.isValidBIC('INGDEFFXXX');
ibantools.isValidBIC('INGDDEFFXXX');
```

Current regex:
`^[a-zA-Z]{6}[a-zA-Z0-9]{2}[A-Z0-9]{0,3}$`

Your regex seems to be to lazy. How about this one https://stackoverflow.com/a/19057449/4300087 ?
It doesn't detect the BIC from above as valid:
`^[a-z]{6}[2-9a-z][0-9a-np-z]([a-z0-9]{3}|x{3})?$`

**Comment by Simplify** [comment]
@FireEmerald Thank you for reporting this problem and sorry about my delayed reaction. I just released version 1.5.1 that fixes this issue.
