### ISSUE TITLE
[Feature]: adding valid random IBAN generation based on country code

### ISSUE THREAD

**Issue by clemgbld** [Simplify/ibantools#536]
I recently had the need to generate valid random IBAN for testing purpose on a project at work and i couldn't find any library that can do that.
So i did it with the help of ibantools (the project i work on already use it) but i think it could be nice to have this feature directly in ibantools.
I will understand if you think that this feature is not in the spirit of the library and close the issue.

**Comment by kevinramharak** [comment]
@clemgbld I would recommend libraries that focus on generating fake data like [faker.js](https://fakerjs.dev/). Faker.js provides the [`iban()`](https://fakerjs.dev/api/finance.html#iban) method that allows for passing the country code and if its formatted with spaces or not. I think generating fake data is out of the scope for this library.

**Comment by clemgbld** [comment]
@kevinramharak I really need the iban to be valid and unfortunately there is some times when faker doesn't generate valid iban so i will stick to my custom algorithm i guess, thanks for you reply i will close the issue
