### ISSUE TITLE
composeIBAN returns null even for the example from the docs

### ISSUE THREAD

**Issue by red-sight** [Simplify/ibantools#54]
### Expected behavior
returns NL91ABNA0417164300 

### Actual behavior
returns null

### Steps to reproduce the behavior
![image](https://user-images.githubusercontent.com/2592568/119320870-b39c4500-bc84-11eb-810a-0ad28b9f489a.png)

![image](https://user-images.githubusercontent.com/2592568/119320903-bbf48000-bc84-11eb-8d64-dc2c5d7db4de.png)

ibantools version: latest
system: Ubuntu 20.04
Nove version: 12.18

**Comment by Simplify** [comment]
Hi @red-sight,
Sorry about late reaction. Docs are incorrect. Correct usage is this:
```javascript
ibantools.composeIBAN({ countryCode: "NL", bban: "ABNA0417164300" });
```
I'll fix documentation. Thank you for reporting this.
