### ISSUE TITLE
Bulgaria is a SEPA country

### ISSUE THREAD

**Issue by endbay** [Simplify/ibantools#56]
Due to the official EU site, Bulgaria is part of the SEPA zone.
Source: https://www.ecb.europa.eu/paym/integration/retail/sepa/html/index.en.html

### Expected behavior
IBANTools.isSEPACountry('BG') => true

### Actual behavior
IBANTools.isSEPACountry('BG') => false

**Comment by Simplify** [comment]
Thanks for reporting this and sorry about my late reaction. This is solved and will be released today.
