### ISSUE TITLE
SN IBAN is considered invalid when it is actually valid

### ISSUE THREAD

**Issue by mithrandyrStrider** [Simplify/ibantools#63]
Expected behavior
SN IBAN SN08SN0100152000048500003035 to be valid

Actual behavior
SN IBAN SN08SN0100152000048500003035 is invalid

validate SN08SN0100152000048500003035 with isValidIBAN function return invalid. Seems like regex evaluation in checkFormatBBAN return false;
Also I check  https://www.iban.com/iban-checker with the same IBAN number and says it is valid.

**Comment by Simplify** [comment]
@mithrandyrStrider Thank you for your report and sorry for my late reaction. Bug is solved now and I will make new release today.
