### ISSUE TITLE
[Question] Does `countrySpecs` contain all `ISO 3166-1 alpha-2` country codes?

### ISSUE THREAD

**Issue by victormihalache** [Simplify/ibantools#65]
Title. 

I need to know that because I have another library that uses the `ISO 3166-1 alpha-2` codes and I want to know beforehand if this list is compatible with the official one or if there are any exceptions or important notices.

**Comment by Simplify** [comment]
Hi, sorry about late reaction.
No, it does not contain list of all countries. Only those that use IBAN or BIC.
