### ISSUE TITLE
Valid ES IBAN is considered invalid

### ISSUE THREAD

**Issue by endbay** [Simplify/ibantools#76]
**Describe the bug**
Valid Spain IBAN ES4901825500610201630983 is considered invalid.

**To Reproduce**
```
    const iban = 'ES4901825500610201630983';
    console.log(IBANTools.isValidIBAN(iban));
```

**Expected behavior**
Should return `true`, but does return `false`

**Comment by Simplify** [comment]
@endbay Thank you for your bug report. 
Issue is fixed and release 4.0.1 is created.
