### ISSUE TITLE
Extend extractIban to extract bankAccount

### ISSUE THREAD

**Issue by halafi** [Simplify/ibantools#77]
### Expected behavior

```
// returns {iban: "NL91ABNA0417164300", bban: "ABNA0417164300", countryCode: "NL", bankAccount: "0417164300" valid: true}
ibantools.extractIBAN("NL91 ABNA 0417 1643 00");
```

### Actual behavior

```
// returns {iban: "NL91ABNA0417164300", bban: "ABNA0417164300", countryCode: "NL", valid: true}
ibantools.extractIBAN("NL91 ABNA 0417 1643 00");
```

### Steps to reproduce the behavior

the length of bank account number varies per country

**Comment by Simplify** [comment]
Extraction of account number, bank and branch code is planned for future release.

**Comment by AtoianAvetik** [comment]
Hi! Any progress of this?

**Comment by Simplify** [comment]
Sorry that it took me almost two years to implement this. It works only for countries where I have data to do extraction. Except `accountNumber`, `bankIdentifier` and `branchIdentifier` is also extracted, when available.
I'll make release today or tomorrow with this code.
