### ISSUE TITLE
Check country code in isValidBIC

### ISSUE THREAD

**Issue by albanm** [Simplify/ibantools#8]
ibantools only checks the regexp in isValidBIC, and this regexp can match a lot of invalid strings.

From the documentation, it seems that checking the country code is the only thing we can do to make this a little more restrictive.

Currently I use this module to do it myself : https://www.npmjs.com/package/iso-3166-1-alpha-2

**Comment by Simplify** [comment]
Hi @albanm, thanks for this report and suggestion.  It's implemented in [2.0.0 release](https://github.com/Simplify/ibantools/blob/master/ChangeLog#L6).
