### ISSUE TITLE
Denial of Service or hang when validating ".."

### ISSUE THREAD

**Issue by Wendelstein7** [Simplify/ibantools#83]
**Describe the bug**
Validating IBAN input `..` (two dots) will hang the `validateIBAN()` function forever and eat (cpu) resources.

**To Reproduce**
```js
const ibantools = require('ibantools');
ibantools.validateIBAN('..'); // This function will never return
```

**Expected behavior**
I expected the validator to return that the IBAN is invalid. However, the function validateIBAN never returns with this specific input.

**Environment:**
JavaScript in a Vue/vite web-app context, but I _do not expect_ this to be relevant.

**Comment by Simplify** [comment]
Hi @Wendelstein7,
Thank you for your report and sorry about late reaction.
Issue is fixed now. I'll make new release later today.
