### ISSUE TITLE
Change package.json jsnext:main to module

### ISSUE THREAD

**Issue by tkrotoff** [Simplify/ibantools#9]
Inside [package.json](https://github.com/Simplify/ibantools/blob/2.0.0/package.json#L15) `jsnext:main` has been superseded by `module`, see https://www.reddit.com/r/javascript/comments/5jwg9c/confused_about_fields_module_and_jsnextmain_in/

**Comment by Simplify** [comment]
@tkrotoff  Thank you for your report. Issue is addressed and will be released in next version. Sorry that it took so long...
